name: Test workflow
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: arc-runner-set
    steps:
      #- uses: docker://ubuntu:latest
      #  with:
      #    args: echo test
      - name: test
        run: echo test && sleep 60
