name: Test workflow
on:
  workflow_dispatch:
jobs:
  test1:
      runs-on: arc-runner-set
      steps:
        - name: step1
          run: | 
            id
            echo "step1"
        - name: docker
          uses: docker://ubuntu:latest
  test2:
    runs-on: arc-runner-set
    steps:
      - name: step2
        run: echo "step2"
