name: Test workflow
on:
  workflow_dispatch:
jobs:
  test1:
      runs-on: arc-runner-set
      services:
        redis:
          image: redis
      container:
          image: ubuntu
          options: --cpus 1
      steps:
        - name: step1
          run: | 
            id
            echo "step1"
  test2:
    runs-on: arc-runner-set
    steps:
      - name: step2
        run: echo "step2"
